name: web3dart
description: Dart library to connect to Ethereum clients. Send transactions and interact with smart contracts!
version: 1.2.3
homepage: https://github.com/simolus3/web3dart

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  pointycastle: ^3.0.1
  convert: ^3.0.0
  meta: ^1.3.0
  http: ^0.13.3
  uuid: ^3.0.4
  isolate: ^2.0.0
  typed_data: ^1.3.0
  stream_channel: ^2.1.0
  json_rpc_2: ^3.0.1

  # logger:
  # dart utils:
  dust:
    git:
      url: https://github.com/better-dart/pkg.git   # repo http clone url
      ref: "2ec4156"                                # git tag or git commit-id
      path: packages/dust                           # pkg path


dev_dependencies:
  web_socket_channel: ^2.1.0
  path: ^1.8.0
  test: ^1.17.4
  mockito: ^5.0.8
  coverage: ^1.0.2
